# Generated by Django 5.1.6 on 2025-02-27 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='RSI_14',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='SMA_200',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='SMA_50',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='current_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='new_high',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stock',
            name='new_low',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stock',
            name='volume_spike',
            field=models.BooleanField(default=False),
        ),
    ]
