# Generated by Django 5.1.6 on 2025-02-27 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_stock_rsi_14_stock_sma_200_stock_sma_50_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='RS_SP500',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='SMA_200_week',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='SMA_50_week',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='WMA_30_week',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
