# Generated by Django 5.1.6 on 2025-03-01 01:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_stock_rs_sp500_stock_sma_200_week_stock_sma_50_week_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndustryGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='industry_groups', to='stocks.sector')),
            ],
        ),
        migrations.AddField(
            model_name='stock',
            name='industry_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stocks', to='stocks.industrygroup'),
        ),
    ]
